version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    env_file: [ .env ]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE:   ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports: [ "3306:3306" ]

  migrate:
    build: .
    env_file: [ .env ]
    depends_on: [ db ]
    # wait for the DB, then run migrations
    entrypoint:
      - sh
      - -c
      - |
        until nc -z $DB_HOST $DB_PORT; do sleep 1; done
        exec migrate

  api:
    build: .
    env_file: [ .env ]
    depends_on: [ db, migrate ]
    ports: [ "8080:8080" ]
    # uses ENTRYPOINT ["api"]

volumes:
  db_data:
