version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    env_file: [ .env ]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE:   ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports: [ "3306:3306" ]

  migrate:
    image: gorestapi:latest    # same image as api
    build: .
    env_file: [ .env ]
    environment:
      - MIGRATIONS_PATH=/app/cmd/migrate/migrations
    depends_on:
      - db
    working_dir: /app
    entrypoint:
      - sh
      - -c
      - |
        echo "⏳ waiting for db..."
        until nc -z $DB_HOST $DB_PORT; do sleep 1; done
        echo "🗄️ applying migrations..."
        migrate up

  api:
    image: gorestapi:latest
    build: .
    env_file: [ .env ]
    depends_on:
      - db
      - migrate
    ports: [ "8080:8080" ]
    working_dir: /app
    entrypoint:
      - sh
      - -c
      - |
        echo "⏳ waiting for db..."
        until nc -z $DB_HOST $DB_PORT; do sleep 1; done
        echo "✅ starting API"
        api

volumes:
  db_data:
